sudo: required

services:
  - docker

script:
  - docker build -t gldraphael/evlog -f ./src/Evlog.Web/Dockerfile .

deploy:
  provider: script
  script: docker push gldraphael/evlog
  on:
    branch: master
