sudo: required
language: csharp
mono: none
dotnet: 3.0.100-preview8-013656
dist: xenial

services:
  - docker

script:
  - dotnet tool install --tool-path ./tools Cake.Tool
  - ./tools/dotnet-cake --target=travis

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
