sudo: required

services:
  - docker

script:
  - docker build -t gldraphael/evlog -f ./src/Evlog.Web/Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push gldraphael/evlog

deploy:
  provider: script
  script: echo Deploy
  on:
    branch: master
