sudo: required
language: csharp
mono: none
dotnet: 2.2.104
dist: xenial

services:
  - docker

script:
  - dotnet tool install --global Cake.Tool
  - dotnet cake --target=travis

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
