sudo: required
language: generic

services:
  - docker

script:
  - docker build -t gldraphael/evlog -f ./src/Evlog.Web/Dockerfile .

deploy:
  provider: script
  script: ../scripts/deploy.sh
  on:
    branch: master
