sudo: required
language: csharp
dist: xenial
mono: none
dotnet: 3.1.101

services:
  - docker

script:
  - dotnet tool restore
  - dotnet cake --target=travis

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: dev
