# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pr:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK 5.0.302'
  inputs:
    packageType: sdk
    version: 5.0.302
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet tool restore
    dotnet cake --target=azure-pipelines
  displayName: 'Build & run tests'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: always()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: tests/**/test_result.xml
