version: '3.4'

services:
  evlog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MySql=Server=db;Port=3306;Database=evlogdb;User=root;Password=jRcnDaTMd4QrwnmN6qstAKsj;
    ports:
      - "8080:80"

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=jRcnDaTMd4QrwnmN6qstAKsj
