version: '3.4'

services:

  evlog:
    image: gldraphael/evlog
    restart: on-failure
    build:
      context: .
      dockerfile: src/Evlog.Web/Dockerfile
    depends_on:
      - db

  db:
    image: mysql:8.0.16
    restart: unless-stopped
