version: '3.4'

services:

  evlog.web:
    image: evlog
    build:
      context: .
      dockerfile: src/Evlog.Web/Dockerfile
    depends_on:
      - db

  db:
    image: mongo
    restart: unless-stopped
