version: '3.4'

services:

  evlog.web:
    image: gldraphael/evlog
    build:
      context: .
      dockerfile: src/Evlog.Web/Dockerfile
    depends_on:
      - db

  evlog.admin:
    image: gldraphael/evlog-admin
    build:
      context: ./src/AdminClient
      dockerfile: Dockerfile

  db:
    image: mongo
    restart: unless-stopped
