<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.40.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Slugify.Core" Version="5.1.1" />
  </ItemGroup>

</Project>
